name: measuretf
channels:
  - defaults
  - conda-forge
dependencies:
  - python
  - numpy
  - scipy
  - matplotlib
  - jupyter
  - nose
  - pip:
    - sounddevice
    - tqdm
    - ipdb
    - response
